import { StyleSheet } from "react-native";

export const estilos = StyleSheet.create({
  fundo:{
    alignItems:"center",
    backgroundColor:"#c092dcff",
    height:"100%",
    width:"100%"
  },
  banner:{
    fontSize:32,
    fontWeight:"bold",
    margin:50
  },
  lista:{
    width:"100%",
    alignItems:"center"
  },
  item:{
    alignItems:"center",
    justifyContent:"space-between",
    height:250, 
    width:"50%",
    backgroundColor:"#efd4ffff",
    borderWidth:1,
    borderColor:"#000000",
    marginBottom:30
  },
  titulo:{
    fontSize:20,
    fontWeight:"bold",
    padding:15
  },
  descricao:{
    color:"#000000",
    padding:15
  },
  nav:{
    justifyContent:"space-around",
    backgroundColor:"#52195fff",
    width:"100%",
    flexDirection:"row",
    padding:15
  },
  navText:{
    fontSize:20,
    fontWeight:"bold",
    color:"#ffffffff"
  }
})